services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: pip install -r render-requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port --log-level info main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false